BEGIN TRANSACTION;

CREATE TABLE EMPLOYEES(DEPARTMENT_ID integer, NAME text PRIMARY KEY, SALARY float, LEAD integer);

INSERT INTO EMPLOYEES VALUES(1, 'Nikita Petrov', 1500, 0);
INSERT INTO EMPLOYEES VALUES(1, 'Petr Ivanov', 2500, 1); /* LEAD*/
INSERT INTO EMPLOYEES VALUES(1, 'Kvatnik Stepanov', 3000, 0);
INSERT INTO EMPLOYEES VALUES(1, 'Olga Sharij', 3500, 0);
INSERT INTO EMPLOYEES VALUES(2, 'Alex Fix', 1000, 0);
INSERT INTO EMPLOYEES VALUES(2, 'Sergey Sergeenko', 2800, 1); /*LEAD*/
INSERT INTO EMPLOYEES VALUES(3, 'Dmitry Kaban', 2650, 1); /*LEAD*/
INSERT INTO EMPLOYEES VALUES(3, 'Kirill Orel', 2480, 0);
INSERT INTO EMPLOYEES VALUES(3, 'Eldar Popov', 2800, 0);
COMMIT;

SELECT * FROM EMPLOYEES;

BEGIN TRANSACTION;

CREATE TABLE DEPARTMENTS(DEPARTMENT_ID integer PRIMARY KEY, DEPARTMENT_NAME text);

INSERT INTO DEPARTMENTS VALUES(1, 'Management Department');
INSERT INTO DEPARTMENTS VALUES(2, 'Frontend Developers Department');
INSERT INTO DEPARTMENTS VALUES(3, 'DevOps Developers Department');
COMMIT;

SELECT * FROM DEPARTMENTS;

SELECT DEPARTMENTS.DEPARTMENT_NAME, EMPLOYEES.NAME
FROM DEPARTMENTS
INNER JOIN EMPLOYEES
ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
MPLOYEES.DEPARTMENT_ID
WHERE EMPLOYEES.LEAD = 0
AND EMPLOYEES.SALARY >
(SELECT EMPLOYEES.SALARY FROM EMPLOYEES WHERE EMPLOYEES.LEAD = 1);
